#!/usr/bin/env python3
"""
make_keys: nano_provision.py for the phone. Writes app/.../key/DemoKeys.kt with the
two demo keys the NFC tags stand for. Like the Nano, the app gets only salted
commitments (never the name or date of birth) plus the key id and device secret.
The output holds a real device secret, so it is gitignored: run this before building.

    python3 tools/make_keys.py --registry //wsl.localhost/Ubuntu/home/nathan/hackgt26/nano_registry.json

PASS key: Nathan Donagi, the same key as the Arduino (its key_id/device_secret
          come from nano_registry.json, so the servers accept its proofs).
FAIL key: someone else, under 18, deliberately NOT in nano_registry.json, so
          every check fails: the key itself says no to age and name checks,
          and the servers reject its sign-up proofs.

Commitment format (same as kagi_nano.ino / nano_provision.py):
    C = PBKDF2-HMAC-SHA256(SHA256(json(parts)), salt, ITERS, 32), stored as salt || C
    L1       ["L1","full_name",[first,last]]
    OVER t   ["OVER",t]            or random decoy bytes if under t
"""

import argparse
import datetime
import hashlib
import json
import secrets
from pathlib import Path

ITERS = 10_000
OUT = Path(__file__).resolve().parent.parent / "app/src/main/java/com/example/kagi/key/DemoKeys.kt"


def commit(parts) -> bytes:
    salt = secrets.token_bytes(32)
    msg = json.dumps(parts, separators=(",", ":")).encode()
    return salt + hashlib.pbkdf2_hmac("sha256", hashlib.sha256(msg).digest(), salt, ITERS, 32)


def norm(name: str) -> str:
    return " ".join(name.split()).lower()


def age_on(dob: datetime.date, day: datetime.date) -> int:
    return day.year - dob.year - ((day.month, day.day) < (dob.month, dob.day))


def key(label, key_id, secret, first, last, dob):
    age = age_on(datetime.date.fromisoformat(dob), datetime.date.today())
    c = {"L1": commit(["L1", "full_name", [norm(first), norm(last)]])}
    for t in (18, 21):
        c[f"OVER{t}"] = commit(["OVER", t]) if age >= t else secrets.token_bytes(64)
    lines = [f'        keyId = "{key_id}",',
             f'        deviceSecret = "{secret}",',
             f"        iters = {ITERS},"]
    lines += [f'        {k.lower()} = "{v.hex()}",' for k, v in c.items()]
    return f"    val {label} = PhoneKey(\n" + "\n".join(lines) + "\n    )\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--registry", type=Path, required=True)
    a = p.parse_args()
    reg = json.loads(a.registry.read_text())
    nathan = reg["1b120e0f3e770faccbf4a262"]
    body = (
        "package com.example.kagi.key\n\n"
        "// Generated by tools/make_keys.py; do not edit. Commitments only, no personal data.\n"
        "object DemoKeys {\n"
        "    /** The pass key's device secret, as in nano_registry.json (PhoneKeyTest checks proofs against it). */\n"
        f'    const val PASS_SECRET = "{nathan["device_secret"]}"\n\n'
        "    /** Nathan Donagi's key, the same one as the Arduino (registered on the servers). */\n"
        + key("PASS", nathan["key_id"], nathan["device_secret"], "Nathan", "Donagi", "2005-09-21")
        + "\n    /** Someone else, under 18, not registered anywhere: every check fails. */\n"
        + key("FAIL", secrets.token_hex(12), secrets.token_hex(32), "Alex", "Rivera", "2012-03-14")
        + "}\n"
    )
    OUT.write_text(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
