/*
 * kagi_nano: the kagi attribute-bound key, living on an Arduino Nano.
 *
 * The Nano holds the key (salted PBKDF2 commitments, never the facts). A PC
 * sends queries over USB serial and gets back yes/no. On yes, the Nano also
 * returns an HMAC proof over the PC's random challenge, so the PC knows the
 * answer came from this device and isn't a replay.
 *
 * No libraries needed. Board: Arduino Nano (ATmega328P). Serial: 115200 baud.
 *
 * Commands (one per line):
 *   PING                       -> PONG kagi-nano v1
 *   INFO                       -> INFO id=<hex> iters=<n> fails=<n> tap=<0|1>
 *   SIGN <nonce> <site_id>     -> (TAP while waiting for the button) SIGNED <hmac hex>
 *                                 or TIMEOUT. Used by the unique sign-up flow: the
 *                                 central server checks the HMAC and looks the key up.
 *   AUTH <challenge> k=v;k=v   -> WORKING, then one of
 *                                   AUTHENTICATED <scope> <hmac hex>
 *                                   DENIED
 *                                   LOCKED <seconds>
 *     <challenge> is 1-64 hex chars from the PC, or "-" when typing by hand.
 *     Keys: first_name, last_name, dob (YYYY-MM-DD or MM/DD/YYYY), ssn, pin, over
 *
 * Query kinds (same rules as kagi.py, with date of birth instead of age):
 *   Level 1:  first_name + last_name, optionally dob                 -> L1
 *   Over:     over=18|21 alone (no name needed)                      -> OVER18/OVER21
 *   Level 2:  first_name + last_name + dob + ssn + pin (all needed)  -> L2
 *
 * Commitments: C = PBKDF2-HMAC-SHA256(SHA256(json(parts)), salt, ITERS)
 *   full_name  ["L1","full_name",[first,last]]
 *   dob        ["L1","dob",[first,last],dob]                 (chained on the name)
 *   ssn        ["L2","ssn",[first,last],dob,pin,ssn]         (covers everything)
 *   over T     ["OVER",T]                or random decoy bytes if under T
 *
 * Why this is stronger than the PC-only version: the commitments never leave
 * the chip (there is no command to read them), so the only way to guess is
 * through this serial port, which is rate limited (see LOCKOUT). The failure
 * counter lives in EEPROM, so unplugging the board doesn't reset it. Over
 * queries take no secret input, so there is nothing to guess: they skip the
 * lockout and aren't counted.
 */

#include <EEPROM.h>
#include <avr/pgmspace.h>

// ===== KEY DATA BEGIN (generated by nano_provision.py, do not edit) =====
// Issued 2026-09-26, expires 2027-09-26. Over 18: yes, over 21: yes (decoys look identical).
#define BK_KDF_ITERS 200
static const uint8_t BK_KEY_ID[12] PROGMEM = {
  0x1b, 0x12, 0x0e, 0x0f, 0x3e, 0x77, 0x0f, 0xac, 0xcb, 0xf4, 0xa2, 0x62,
};
static const uint8_t BK_DEVICE_SECRET[32] PROGMEM = {
  0x6a, 0xb7, 0xab, 0x62, 0x46, 0xcc, 0xe0, 0x82, 0x81, 0x33, 0x66, 0x41, 0x75, 0xd7, 0x60, 0x22,
  0x84, 0xeb, 0x54, 0xb5, 0x73, 0x9e, 0x00, 0xed, 0xa4, 0x94, 0x79, 0xdf, 0x31, 0xbe, 0x2d, 0x7e,
};
static const uint8_t BK_C_FULL_NAME[64] PROGMEM = {
  0xbb, 0xf6, 0x20, 0x9f, 0xb3, 0x18, 0x02, 0x48, 0xd4, 0x3e, 0x20, 0x63, 0x4b, 0x6a, 0xcc, 0x82,
  0xfe, 0x39, 0xe8, 0x1b, 0x9d, 0xb5, 0x73, 0x97, 0x4a, 0x32, 0x9e, 0x75, 0x3f, 0x30, 0xe6, 0xa2,
  0xb9, 0x36, 0x44, 0xb3, 0xb0, 0x70, 0xfa, 0xa9, 0x9e, 0x15, 0xf1, 0x33, 0x0d, 0x8b, 0x96, 0xe1,
  0xcc, 0x37, 0x0c, 0x07, 0xcf, 0xb2, 0x08, 0x20, 0x2c, 0x4b, 0xa1, 0xd7, 0x39, 0xec, 0x91, 0x00,
};
static const uint8_t BK_C_DOB[64] PROGMEM = {
  0xbf, 0x50, 0xc8, 0xde, 0xa6, 0x8d, 0x4e, 0xbe, 0x3e, 0x10, 0xf6, 0xfb, 0xd2, 0x36, 0xc1, 0xab,
  0x84, 0xe1, 0x00, 0xb1, 0xbc, 0xd9, 0x99, 0xbf, 0x72, 0x04, 0x7b, 0x18, 0x05, 0x4f, 0x04, 0xf1,
  0x01, 0xb3, 0x9b, 0x53, 0x8c, 0x2c, 0x9f, 0x6d, 0xe8, 0x36, 0x71, 0x5b, 0xcd, 0xb6, 0xea, 0xda,
  0x87, 0xb9, 0xa5, 0x4e, 0x8a, 0x3b, 0x37, 0xd4, 0x6d, 0xb2, 0x18, 0x2a, 0xef, 0x9c, 0x0d, 0xf9,
};
static const uint8_t BK_C_SSN[64] PROGMEM = {
  0x6d, 0x50, 0x2a, 0x56, 0x84, 0xf7, 0x78, 0xd3, 0xb2, 0x5b, 0x5c, 0xa8, 0xa0, 0x0a, 0xf0, 0xca,
  0x6d, 0x9e, 0x9b, 0x38, 0xe2, 0xf0, 0x5f, 0xe0, 0xdc, 0x90, 0x08, 0xee, 0x79, 0xe0, 0xb3, 0xbd,
  0x2a, 0xb1, 0x2a, 0x29, 0x22, 0xdc, 0xee, 0xbb, 0x50, 0xee, 0x1a, 0xa4, 0x81, 0x3f, 0x73, 0x7b,
  0x8b, 0xe1, 0x50, 0x7f, 0xee, 0x2a, 0x7f, 0x68, 0x54, 0x4f, 0xed, 0xe8, 0x58, 0x1a, 0x9b, 0xf8,
};
static const uint8_t BK_C_OVER18[64] PROGMEM = {
  0x95, 0x73, 0x1d, 0x29, 0xb3, 0xa7, 0xf4, 0xcb, 0xc4, 0xe0, 0x53, 0x4c, 0x67, 0x5a, 0x2a, 0xab,
  0xb5, 0x27, 0xfe, 0x7a, 0x9f, 0x62, 0xcf, 0x76, 0xdf, 0x7c, 0x76, 0xb5, 0x93, 0x99, 0xe7, 0xc6,
  0xed, 0xeb, 0xb2, 0xfe, 0x92, 0xbb, 0x37, 0x18, 0x7c, 0x9c, 0x12, 0x78, 0x0b, 0x64, 0x74, 0x07,
  0x81, 0xdc, 0xa7, 0x97, 0x80, 0x3a, 0x38, 0x98, 0x9c, 0x3f, 0xd8, 0xdf, 0x7f, 0x6b, 0xd0, 0xea,
};
static const uint8_t BK_C_OVER21[64] PROGMEM = {
  0xde, 0x06, 0xea, 0x3f, 0xef, 0x24, 0xa8, 0xb5, 0xd9, 0xfd, 0x82, 0x40, 0x8c, 0x88, 0x63, 0xb9,
  0x26, 0x38, 0xd3, 0x4b, 0xe2, 0xc4, 0x28, 0x69, 0x5c, 0x12, 0x44, 0x4c, 0xda, 0x8e, 0x89, 0x29,
  0xd6, 0xf0, 0xbf, 0x74, 0xfd, 0xb4, 0xa7, 0x64, 0x64, 0x76, 0xc5, 0x3d, 0x61, 0xd0, 0x96, 0xeb,
  0xea, 0x0c, 0x6e, 0xf9, 0x07, 0xb4, 0x3d, 0x0d, 0x3d, 0xb4, 0x84, 0x97, 0xee, 0x1c, 0x6b, 0x9c,
};
// ===== KEY DATA END =====

// Each commitment above is 32 bytes of salt followed by the 32-byte PBKDF2 output.

// ---------- LOCKOUT ----------
// Failed guesses are counted in EEPROM. The first FREE_TRIES are instant;
// after that each attempt must wait 15 s, 30 s, 60 s, ... (max ~64 min) since
// the previous attempt or since power-up. A correct level-2 query (which needs
// the PIN) resets the counter; other successes simply don't count as failures.
#define FREE_TRIES 5
#define EE_MAGIC 0     // 4 bytes: start of the key id, so a new key resets the counter
#define EE_FAILS 4

// ---------- TAP BUTTON ----------
// "Tap your key": wire a push button between D2 and GND and set USE_TAP_BUTTON
// to 1. SIGN then waits (built-in LED blinking) until the button is pressed.
// With 0, SIGN answers at once and the phone app asks you to press Enter instead.
#define USE_TAP_BUTTON 0
#define TAP_PIN 2
#define TAP_TIMEOUT_MS 30000UL

#define MAX_LINE 200
#define MAX_NAME 32

enum { F_FIRST = 1, F_LAST = 2, F_DOB = 4, F_SSN = 8, F_PIN = 16, F_OVER = 32 };

struct Sha256 {
  uint32_t h[8];
  uint8_t buf[64];
  uint8_t buflen;
  uint32_t total;
};

struct Query {
  char first[MAX_NAME + 1];
  char last[MAX_NAME + 1];
  char dob[11];
  char ssn[10];
  char pin[5];
  uint8_t over;
  uint8_t has;
};

static char line[MAX_LINE + 1];
static uint8_t line_len = 0;
static bool line_overflow = false;
static unsigned long last_attempt = 0;

// ---------- SHA-256 / HMAC / PBKDF2 ----------

static const uint32_t SHA_K[64] PROGMEM = {
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
};

static const uint32_t SHA_H0[8] PROGMEM = {
  0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
};

static inline uint32_t ror32(uint32_t x, uint8_t n) { return (x >> n) | (x << (32 - n)); }

// 16-word rolling message schedule: 64 bytes of RAM instead of 256.
static void sha256_compress(uint32_t h[8], const uint8_t block[64]) {
  uint32_t w[16];
  for (uint8_t i = 0; i < 16; i++)
    w[i] = (uint32_t)block[4 * i] << 24 | (uint32_t)block[4 * i + 1] << 16 |
           (uint32_t)block[4 * i + 2] << 8 | block[4 * i + 3];
  uint32_t a = h[0], b = h[1], c = h[2], d = h[3], e = h[4], f = h[5], g = h[6], hh = h[7];
  for (uint8_t i = 0; i < 64; i++) {
    uint32_t wi;
    if (i < 16) {
      wi = w[i];
    } else {
      uint32_t w15 = w[(i + 1) & 15], w2 = w[(i + 14) & 15];
      uint32_t s0 = ror32(w15, 7) ^ ror32(w15, 18) ^ (w15 >> 3);
      uint32_t s1 = ror32(w2, 17) ^ ror32(w2, 19) ^ (w2 >> 10);
      wi = w[i & 15] += s0 + w[(i + 9) & 15] + s1;
    }
    uint32_t t1 = hh + (ror32(e, 6) ^ ror32(e, 11) ^ ror32(e, 25)) + ((e & f) ^ (~e & g)) +
                  pgm_read_dword(&SHA_K[i]) + wi;
    uint32_t t2 = (ror32(a, 2) ^ ror32(a, 13) ^ ror32(a, 22)) + ((a & b) ^ (a & c) ^ (b & c));
    hh = g; g = f; f = e; e = d + t1; d = c; c = b; b = a; a = t1 + t2;
  }
  h[0] += a; h[1] += b; h[2] += c; h[3] += d; h[4] += e; h[5] += f; h[6] += g; h[7] += hh;
}

static void sha256_init(Sha256 *c) {
  for (uint8_t i = 0; i < 8; i++) c->h[i] = pgm_read_dword(&SHA_H0[i]);
  c->buflen = 0;
  c->total = 0;
}

static void sha256_update(Sha256 *c, const void *data, uint16_t len) {
  const uint8_t *p = (const uint8_t *)data;
  c->total += len;
  while (len--) {
    c->buf[c->buflen++] = *p++;
    if (c->buflen == 64) {
      sha256_compress(c->h, c->buf);
      c->buflen = 0;
    }
  }
}

static void sha256_str(Sha256 *c, const char *s) { sha256_update(c, s, strlen(s)); }

static void sha256_final(Sha256 *c, uint8_t out[32]) {
  uint32_t bits = c->total << 3;   // messages here are tiny
  uint8_t pad = 0x80;
  sha256_update(c, &pad, 1);
  pad = 0;
  while (c->buflen != 56) sha256_update(c, &pad, 1);
  uint8_t len[8] = {0, 0, 0, 0, (uint8_t)(bits >> 24), (uint8_t)(bits >> 16),
                    (uint8_t)(bits >> 8), (uint8_t)bits};
  sha256_update(c, len, 8);
  for (uint8_t i = 0; i < 8; i++) {
    out[4 * i] = c->h[i] >> 24;
    out[4 * i + 1] = c->h[i] >> 16;
    out[4 * i + 2] = c->h[i] >> 8;
    out[4 * i + 3] = c->h[i];
  }
}

// State after hashing one 64-byte block of (32-byte key) ^ pad.
static void sha256_keyed(Sha256 *c, const uint8_t key[32], uint8_t pad) {
  uint8_t block[64];
  for (uint8_t i = 0; i < 64; i++) block[i] = (i < 32 ? key[i] : 0) ^ pad;
  sha256_init(c);
  sha256_update(c, block, 64);
}

// HMAC-SHA256 with a 32-byte key, split so the keyed states can be reused.
static void hmac_begin(Sha256 *inner, uint32_t outer[8], const uint8_t key[32]) {
  sha256_keyed(inner, key, 0x5c);
  memcpy(outer, inner->h, 32);
  sha256_keyed(inner, key, 0x36);
}

static void hmac_end(Sha256 *inner, const uint32_t outer[8], uint8_t out[32]) {
  uint8_t ih[32];
  sha256_final(inner, ih);
  memcpy(inner->h, outer, 32);
  inner->buflen = 0;
  inner->total = 64;
  sha256_update(inner, ih, 32);
  sha256_final(inner, out);
}

// Same as Python: hashlib.pbkdf2_hmac("sha256", pwd, salt, iters, 32)
static void pbkdf2_sha256(const uint8_t pwd[32], const uint8_t salt[32], uint16_t iters,
                          uint8_t out[32]) {
  static const uint8_t one[4] = {0, 0, 0, 1};
  Sha256 base, c;
  uint32_t outer[8];
  uint8_t u[32];
  hmac_begin(&base, outer, pwd);
  c = base;
  sha256_update(&c, salt, 32);
  sha256_update(&c, one, 4);
  hmac_end(&c, outer, u);
  memcpy(out, u, 32);
  for (uint16_t i = 1; i < iters; i++) {
    c = base;
    sha256_update(&c, u, 32);
    hmac_end(&c, outer, u);
    for (uint8_t j = 0; j < 32; j++) out[j] ^= u[j];
  }
}

// ---------- normalization (ASCII version of kagi.normalize) ----------

// Lowercase, trim, collapse runs of whitespace. Rejects characters that would
// need JSON escaping or aren't plain ASCII, so the JSON below stays trivial.
static bool norm_name(const char *in, char *out) {
  uint8_t n = 0;
  bool space = false;
  for (; *in; in++) {
    char ch = *in;
    if (ch == ' ' || ch == '\t') {
      space = n > 0;
      continue;
    }
    if (ch < 0x21 || ch > 0x7e || ch == '"' || ch == '\\') return false;
    if (space) {
      if (n >= MAX_NAME) return false;
      out[n++] = ' ';
      space = false;
    }
    if (n >= MAX_NAME) return false;
    out[n++] = (ch >= 'A' && ch <= 'Z') ? ch + 32 : ch;
  }
  out[n] = 0;
  return n > 0;
}

// Keeps only digits, dropping spaces (and dashes if allowed). Needs exactly `want` digits.
static bool norm_digits(const char *in, char *out, uint8_t want, bool allow_dash) {
  uint8_t n = 0;
  for (; *in; in++) {
    if (*in == ' ' || *in == '\t' || (allow_dash && *in == '-')) continue;
    if (*in < '0' || *in > '9' || n >= want) return false;
    out[n++] = *in;
  }
  out[n] = 0;
  return n == want;
}

static bool leap(uint16_t y) { return (y % 4 == 0 && y % 100 != 0) || y % 400 == 0; }

// Accepts YYYY-MM-DD, YYYY/MM/DD, MM/DD/YYYY, MM-DD-YYYY (one-digit month/day ok).
// Output: YYYY-MM-DD.
static bool norm_dob(const char *in, char *out) {
  uint16_t part[3] = {0, 0, 0};
  uint8_t digits[3] = {0, 0, 0}, k = 0;
  while (*in == ' ') in++;
  for (; *in && *in != ' '; in++) {
    if (*in == '-' || *in == '/') {
      if (++k > 2) return false;
    } else if (*in >= '0' && *in <= '9') {
      if (++digits[k] > 4) return false;
      part[k] = part[k] * 10 + (*in - '0');
    } else {
      return false;
    }
  }
  while (*in == ' ') in++;
  if (*in || k != 2) return false;
  uint16_t y, m, d;
  if (digits[0] == 4 && digits[1] <= 2 && digits[2] <= 2) {
    y = part[0]; m = part[1]; d = part[2];
  } else if (digits[2] == 4 && digits[0] <= 2 && digits[1] <= 2) {
    m = part[0]; d = part[1]; y = part[2];
  } else {
    return false;
  }
  static const uint8_t mdays[12] = {31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
  if (!digits[1] || !digits[2] || !digits[0]) return false;
  if (y < 1000 || m < 1 || m > 12 || d < 1 || d > mdays[m - 1]) return false;
  if (m == 2 && d == 29 && !leap(y)) return false;
  out[0] = '0' + y / 1000; out[1] = '0' + y / 100 % 10; out[2] = '0' + y / 10 % 10;
  out[3] = '0' + y % 10; out[4] = '-';
  out[5] = '0' + m / 10; out[6] = '0' + m % 10; out[7] = '-';
  out[8] = '0' + d / 10; out[9] = '0' + d % 10; out[10] = 0;
  return true;
}

// ---------- query parsing ----------

// "k=v;k=v;..." -> Query. Unknown, repeated or malformed fields reject the query.
static bool parse_query(char *s, Query *q) {
  memset(q, 0, sizeof *q);
  while (*s) {
    char *end = strchr(s, ';');
    if (end) *end = 0;
    char *eq = strchr(s, '=');
    if (!eq) return false;
    *eq = 0;
    char *key = s, *val = eq + 1;
    while (*key == ' ') key++;
    for (char *t = eq - 1; t >= key && *t == ' '; t--) *t = 0;

    uint8_t bit;
    bool ok;
    if (!strcmp(key, "first_name")) {
      bit = F_FIRST; ok = norm_name(val, q->first);
    } else if (!strcmp(key, "last_name")) {
      bit = F_LAST; ok = norm_name(val, q->last);
    } else if (!strcmp(key, "dob")) {
      bit = F_DOB; ok = norm_dob(val, q->dob);
    } else if (!strcmp(key, "ssn")) {
      bit = F_SSN; ok = norm_digits(val, q->ssn, 9, true);
    } else if (!strcmp(key, "pin")) {
      bit = F_PIN; ok = norm_digits(val, q->pin, 4, false);
    } else if (!strcmp(key, "over")) {
      char t[3];
      bit = F_OVER;
      ok = norm_digits(val, t, 2, false);
      q->over = ok ? (t[0] - '0') * 10 + (t[1] - '0') : 0;
      ok = ok && (q->over == 18 || q->over == 21);
    } else {
      return false;
    }
    if (!ok || (q->has & bit)) return false;
    q->has |= bit;
    if (!end) break;
    s = end + 1;
  }
  return true;
}

// ---------- commitments ----------

static void put_str(Sha256 *c, const char *s) {
  sha256_str(c, "\"");
  sha256_str(c, s);
  sha256_str(c, "\"");
}

static void put_name(Sha256 *c, const Query *q) {
  sha256_str(c, "[");
  put_str(c, q->first);
  sha256_str(c, ",");
  put_str(c, q->last);
  sha256_str(c, "]");
}

// Constant-time: the whole buffer is always compared.
static bool same32(const uint8_t *a, const uint8_t *b) {
  uint8_t diff = 0;
  for (uint8_t i = 0; i < 32; i++) diff |= a[i] ^ b[i];
  return diff == 0;
}

// Which commitment a query is checked against, and the scope it proves.
// Returns NULL for queries that break the rules (these don't count as guesses).
static const uint8_t *pick_commitment(const Query *q, const char **scope) {
  uint8_t has = q->has;
  if (has & F_OVER) {
    if (has != F_OVER) return NULL;                        // over stands alone
    *scope = q->over == 18 ? "OVER18" : "OVER21";
    return q->over == 18 ? BK_C_OVER18 : BK_C_OVER21;
  }
  if (!(has & F_FIRST) || !(has & F_LAST)) return NULL;   // name always needed, both halves
  if (has & F_SSN) {
    if (has != (F_FIRST | F_LAST | F_DOB | F_SSN | F_PIN)) return NULL;
    *scope = "L2";
    return BK_C_SSN;
  }
  if (has & F_PIN) return NULL;                            // a pin alone is meaningless
  *scope = "L1";
  return (has & F_DOB) ? BK_C_DOB : BK_C_FULL_NAME;
}

// One PBKDF2 per query. The L2 commitment covers every level-1 value, and the
// dob commitment covers the name, so checking the single most specific
// commitment gives the same answer as checking each level in turn.
static bool check_query(const Query *q, const uint8_t *commitment) {
  Sha256 c;
  sha256_init(&c);
  if (commitment == BK_C_OVER18 || commitment == BK_C_OVER21) {
    sha256_str(&c, q->over == 18 ? "[\"OVER\",18" : "[\"OVER\",21");
  } else if (commitment == BK_C_SSN) {
    sha256_str(&c, "[\"L2\",\"ssn\",");
    put_name(&c, q);
    sha256_str(&c, ",");
    put_str(&c, q->dob);
    sha256_str(&c, ",");
    put_str(&c, q->pin);
    sha256_str(&c, ",");
    put_str(&c, q->ssn);
  } else if (commitment == BK_C_DOB) {
    sha256_str(&c, "[\"L1\",\"dob\",");
    put_name(&c, q);
    sha256_str(&c, ",");
    put_str(&c, q->dob);
  } else {
    sha256_str(&c, "[\"L1\",\"full_name\",");
    put_name(&c, q);
  }
  sha256_str(&c, "]");

  uint8_t pwd[32], salt[32], want[32], got[32];
  sha256_final(&c, pwd);
  memcpy_P(salt, commitment, 32);
  memcpy_P(want, commitment + 32, 32);
  pbkdf2_sha256(pwd, salt, BK_KDF_ITERS, got);
  return same32(got, want);
}

// ---------- serial output ----------

static void print_hex(const uint8_t *b, uint8_t n, bool progmem) {
  static const char digits[] = "0123456789abcdef";
  for (uint8_t i = 0; i < n; i++) {
    uint8_t v = progmem ? pgm_read_byte(b + i) : b[i];
    Serial.write(digits[v >> 4]);
    Serial.write(digits[v & 15]);
  }
}

// Prints HMAC(device_secret, "<tag>|<key id hex>|<a>|<b>") as hex.
static void print_mac(const char *tag, const char *a, const char *b) {
  static const char digits[] = "0123456789abcdef";
  uint8_t secret[32], mac[32];
  uint32_t outer[8];
  Sha256 c;
  memcpy_P(secret, BK_DEVICE_SECRET, 32);
  hmac_begin(&c, outer, secret);
  memset(secret, 0, 32);
  sha256_str(&c, tag);
  sha256_str(&c, "|");
  for (uint8_t i = 0; i < 12; i++) {
    uint8_t v = pgm_read_byte(BK_KEY_ID + i);
    char hx[2] = {digits[v >> 4], digits[v & 15]};
    sha256_update(&c, hx, 2);
  }
  sha256_str(&c, "|");
  sha256_str(&c, a);
  sha256_str(&c, "|");
  sha256_str(&c, b);
  hmac_end(&c, outer, mac);
  print_hex(mac, 32, false);
}

// proof = HMAC(device_secret, "kagi-nano-v1|<key id hex>|<scope>|<challenge>")
static void send_proof(const char *scope, const char *challenge) {
  Serial.print(F("AUTHENTICATED "));
  Serial.print(scope);
  Serial.print(' ');
  print_mac("kagi-nano-v1", scope, challenge);
  Serial.println();
}

// ---------- lockout ----------

static uint8_t get_fails() { return EEPROM.read(EE_FAILS); }
static void set_fails(uint8_t n) { EEPROM.update(EE_FAILS, n); }

static unsigned long cooldown_ms(uint8_t fails) {
  if (fails < FREE_TRIES) return 0;
  uint8_t shift = fails - FREE_TRIES;
  if (shift > 8) shift = 8;
  return (15000UL) << shift;
}

// ---------- commands ----------

static bool valid_challenge(const char *s) {
  if (!strcmp(s, "-")) return true;
  uint8_t n = 0;
  for (; *s; s++, n++) {
    bool hex = (*s >= '0' && *s <= '9') || (*s >= 'a' && *s <= 'f');
    if (!hex || n >= 64) return false;
  }
  return n > 0;
}

static void cmd_auth(char *args) {
  // args = "<challenge> <query>"
  while (*args == ' ') args++;
  char *sp = strchr(args, ' ');
  if (!sp) {
    Serial.println(F("ERR usage: AUTH <challenge> first_name=..;last_name=..;..."));
    return;
  }
  *sp = 0;
  char *challenge = args;
  if (!valid_challenge(challenge)) {
    Serial.println(F("ERR challenge must be 1-64 lowercase hex chars, or -"));
    return;
  }

  Query q;
  const char *scope = NULL;
  const uint8_t *commitment = NULL;
  if (parse_query(sp + 1, &q)) commitment = pick_commitment(&q, &scope);
  if (!commitment) {
    Serial.println(F("DENIED"));   // like kagi.py: no hint about what was wrong
    return;
  }

  // Over queries have no secret input, so they aren't guesses: no lockout, no count.
  bool guess = strncmp(scope, "OVER", 4) != 0;
  uint8_t fails = get_fails();
  if (guess) {
    unsigned long wait = cooldown_ms(fails), since = millis() - last_attempt;
    if (since < wait) {
      Serial.print(F("LOCKED "));
      Serial.println((wait - since + 999) / 1000);
      return;
    }
    // Count the attempt as a failure BEFORE checking, so pulling the power
    // mid-check can't be used to dodge the counter.
    last_attempt = millis();
    set_fails(fails < 255 ? fails + 1 : 255);
  }
  Serial.println(F("WORKING"));

  if (check_query(&q, commitment)) {
    if (guess) set_fails(!strcmp(scope, "L2") ? 0 : fails);
    send_proof(scope, challenge);
  } else {
    Serial.println(F("DENIED"));
  }
  memset(&q, 0, sizeof q);
}

static bool valid_site(const char *s) {
  uint8_t n = 0;
  for (; *s; s++, n++) {
    bool ok = (*s >= 'a' && *s <= 'z') || (*s >= '0' && *s <= '9') || *s == '.' || *s == '-';
    if (!ok || n >= 64) return false;
  }
  return n > 0;
}

static bool wait_for_tap() {
#if USE_TAP_BUTTON
  Serial.println(F("TAP"));
  unsigned long start = millis();
  while (millis() - start < TAP_TIMEOUT_MS) {
    digitalWrite(LED_BUILTIN, (millis() / 150) & 1);
    if (digitalRead(TAP_PIN) == LOW) {
      delay(30);                                   // debounce
      if (digitalRead(TAP_PIN) == LOW) {
        digitalWrite(LED_BUILTIN, LOW);
        while (digitalRead(TAP_PIN) == LOW) {}     // wait for release
        return true;
      }
    }
  }
  digitalWrite(LED_BUILTIN, LOW);
  return false;
#else
  return true;
#endif
}

// SIGN <nonce> <site_id>: the key's answer to a unique sign-up challenge.
// proof = HMAC(device_secret, "kagi-nano-sign-v1|<key id hex>|<site_id>|<nonce>")
// It reveals nothing about the person; the central server maps the key id to
// an opaque person id it got from the authority at provisioning.
static void cmd_sign(char *args) {
  while (*args == ' ') args++;
  char *sp = strchr(args, ' ');
  if (!sp) {
    Serial.println(F("ERR usage: SIGN <nonce hex> <site_id>"));
    return;
  }
  *sp = 0;
  char *nonce = args, *site = sp + 1;
  while (*site == ' ') site++;
  if (!strcmp(nonce, "-") || !valid_challenge(nonce) || !valid_site(site)) {
    Serial.println(F("ERR nonce must be 1-64 lowercase hex chars, site_id [a-z0-9.-]"));
    return;
  }
  if (!wait_for_tap()) {
    Serial.println(F("TIMEOUT"));
    return;
  }
  Serial.print(F("SIGNED "));
  print_mac("kagi-nano-sign-v1", site, nonce);
  Serial.println();
}

static void handle_line(char *s) {
  while (*s == ' ') s++;
  if (!strcmp(s, "PING")) {
    Serial.println(F("PONG kagi-nano v1"));
  } else if (!strcmp(s, "INFO")) {
    Serial.print(F("INFO id="));
    print_hex(BK_KEY_ID, 12, true);
    Serial.print(F(" iters="));
    Serial.print(BK_KDF_ITERS);
    Serial.print(F(" fails="));
    Serial.print(get_fails());
    Serial.print(F(" tap="));
    Serial.println(USE_TAP_BUTTON);
  } else if (!strncmp(s, "AUTH ", 5)) {
    cmd_auth(s + 5);
  } else if (!strncmp(s, "SIGN ", 5)) {
    cmd_sign(s + 5);
  } else if (*s) {
    Serial.println(F("ERR unknown command (PING, INFO, AUTH, SIGN)"));
  }
}

void setup() {
  Serial.begin(115200);
#if USE_TAP_BUTTON
  pinMode(TAP_PIN, INPUT_PULLUP);
  pinMode(LED_BUILTIN, OUTPUT);
#endif
  // A different key id means a freshly provisioned key: start its counter at 0.
  bool fresh = false;
  for (uint8_t i = 0; i < 4; i++)
    if (EEPROM.read(EE_MAGIC + i) != pgm_read_byte(BK_KEY_ID + i)) fresh = true;
  if (fresh) {
    for (uint8_t i = 0; i < 4; i++) EEPROM.update(EE_MAGIC + i, pgm_read_byte(BK_KEY_ID + i));
    set_fails(0);
  }
  last_attempt = millis();   // a reboot starts the cooldown over, it doesn't skip it
  Serial.print(F("READY kagi-nano v1 id="));
  print_hex(BK_KEY_ID, 12, true);
  Serial.println();
}

void loop() {
  while (Serial.available()) {
    char ch = Serial.read();
    if (ch == '\n' || ch == '\r') {
      if (line_overflow) {
        Serial.println(F("ERR line too long"));
      } else if (line_len) {
        line[line_len] = 0;
        handle_line(line);
      }
      line_len = 0;
      line_overflow = false;
    } else if (line_len < MAX_LINE) {
      line[line_len++] = ch;
    } else {
      line_overflow = true;
    }
  }
}
